cat << EOF > $ROOT/package.json
{
  "private": true,
  "devDependencies": {
    "@babel/cli": "^7.8.4",
    "@babel/core": "^7.9.6",
    "@babel/preset-env": "^7.9.6",
    "@babel/preset-react": "^7.9.4",
    "@babel/preset-typescript": "^7.9.0",
    "@commitlint/cli": "^8.3.5",
    "@commitlint/config-conventional": "^8.3.4",
    "@fullhuman/purgecss-loader": "^1.0.0",
    "@testing-library/react": "^10.0.4",
    "@types/classnames": "^2.2.10",
    "@types/jest": "^25.2.2",
    "@types/react": "^16.9.35",
    "@types/react-dom": "^16.9.8",
    "@types/react-select": "^3.0.13",
    "@typescript-eslint/eslint-plugin": "^2.33.0",
    "@typescript-eslint/parser": "^2.33.0",
    "babel-loader": "^8.1.0",
    "clean-webpack-plugin": "^3.0.0",
    "css-loader": "^3.5.3",
    "cssnano": "^4.1.10",
    "eslint": "^7.0.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-react": "^7.20.0",
    "file-loader": "^6.0.0",
    "glob": "^7.1.6",
    "html-loader": "^1.1.0",
    "html-webpack-plugin": "^4.3.0",
    "husky": "^4.2.5",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^26.0.1",
    "lint-staged": "^10.2.2",
    "mini-css-extract-plugin": "^0.9.0",
    "npm-run-all": "^4.1.5",
    "postcss-loader": "^3.0.0",
    "postcss-preset-env": "^6.7.0",
    "prettier": "^2.0.5",
    "pretty-quick": "^2.0.1",
    "style-loader": "^1.2.1",
    "typescript": "^3.9.2",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.11",
    "webpack-dev-server": "^3.11.0"
  },
  "dependencies": {
    "classnames": "^2.2.6",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-icons": "^3.10.0",
    "react-select": "^3.1.0",
    "tailwindcss": "^1.4.6"
  },
  "scripts": {
    "build": "webpack --env.production",
    "start": "webpack-dev-server",
    "format": "pretty-quick \"**/*.+(js|jsx|ts|tsx|json|md|html|css|scss)\"",
    "format:check": "yarn format --check",
    "format:staged": "yarn format --staged",
    "types:check": "tsc",
    "lint": "eslint --ignore-path .gitignore --ext js,ts,tsx .",
    "lint:staged": "lint-staged -c .lintstagedrc.es.json",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:debug": "node --inspect-brk ./node_modules/.bin/jest --runInBand --watch",
    "test:staged": "lint-staged -c .lintstagedrc.test.json",
    "validate:precommit": "run-s format:staged lint:staged && run-p test:staged types:check build"
  }
}
EOF